### ISSUE TITLE
pip install http_status "not working"

### ISSUE THREAD

**Issue by nueverest** [DanielOaks/http_status#1]
On windows I tried:
`pip install http_status`

And I got:

```
C:\...>pip install http_status
Downloading/unpacking http-status
  Could not find a version that satisfies the requirement http-status (from vers
ions: 0.1.0a)
Cleaning up...
No distributions matching the version for http-status
Storing debug log for failure in C:\...\pip\pip.log
```

**Comment by DanielOaks** [comment]
My best guess is that this is due to it being an 'alpha' package in pypi. I'll try to throw out an actual decent release in a little bit, once we get a few little issues sorted.

For now, try this:

```
pip install --pre http_status
```

**Comment by DanielOaks** [comment]
I've now got it up as a Beta package, 0.2.0b, since I'm getting closer to the point of calling it production-ready. After a few days of being fairly stable, I'll throw up a 1.0.0 release which will fix this issue proper.

**Comment by nueverest** [comment]
Sounds great.

On Tue, Jun 3, 2014 at 2:21 AM, Daniel Oaks notifications@github.com
wrote:

> I've now got it up as a Beta package, 0.2.0b, since I'm getting closer to
> the point of calling it production-ready. After a few days of being fairly
> stable, I'll throw up a 1.0.0 release which will fix this issue proper.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DanielOaks/http_status/issues/1#issuecomment-44942020
> .

## 

Chad Nelson
928-274-1546

**Comment by DanielOaks** [comment]
Alright, just pushed 1.0.0 to PyPi. Gonna leave this open for a little bit, just to make sure, but it should be installable properly now.
