### ISSUE TITLE
Non Numeric Code and codes less than 100

### ISSUE THREAD

**Issue by nueverest** [DanielOaks/http_status#2]
The code currently accepts non-numeric codes and codes less than 100 as keys to the dict.  

Currently RFC 2616 only provides codes in the form of positive Integers from 100-599.
Reference: http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by nueverest** [comment]
I added a formencode validator.  See my fork.

**Comment by DanielOaks** [comment]
Merged in, thanks for catching this for me!
